import { AutomationEngine } from '@/core/AutomationEngine';
import type {
  ActionCommand,
  AutomationConfig,
  EventCallback,
  EventType,
  ExecutionOptions,
  ExecutionResult,
  FormLibrary,
  PageContext,
  ScreenshotOptions,
  WebAutomataAPI,
} from '@/types';
import { AutomationError } from '@/types';

export { AutomationEngine } from '@/core/AutomationEngine';
export { ActionExecutor } from '@/actions/ActionExecutor';
export { DOMActions } from '@/actions/DOMActions';
export { FormRegistry } from '@/forms/FormRegistry';
export { EnhancedFormDetector } from '@/forms/EnhancedFormDetector';
export { ContextCapture } from '@/context/ContextCapture';
export {
  ClickGuide,
  ResearchGuide,
  buildGuideRequest,
  clearHighlight,
  createClickGuide,
  createResearchGuide,
  createTypeSafeDecider,
  mountJevGuide,
  observePage,
  paintHighlight,
} from '@/guide';

export type {
  ActionCommand,
  ActionType,
  AutomationConfig,
  AutomationLocationProvider,
  AutomationRoot,
  AutomationEvent,
  ClickOptions,
  ContextCaptureConfig,
  ElementContext,
  ErrorCode,
  EventCallback,
  EventType,
  ExecutionResult,
  ExecutionOptions,
  FillOptions,
  FormAPI,
  FormContext,
  FormFieldContext,
  FormFieldValue,
  FormFieldValueType,
  FormFillResult,
  FormLibrary,
  FormRegistryConfig,
  NavigationOptions,
  PageContext,
  ScreenshotOptions,
  ViewportInfo,
  WaitOptions,
  WebAutomataAPI,
} from '@/types';

export type {
  ClickGuideOptions,
  GuideObservationOptions,
  ResearchEvidence,
  ResearchGuideOptions,
  ResearchResult,
  GuideControl,
  GuideDecideResult,
  GuideDecider,
  GuideElement,
  GuideHistoryEntry,
  GuideObservation,
  GuideOperation,
  GuideStepResult,
  JevGuideSession,
  MountJevGuideOptions,
  SystemOneRequest,
  TypeSafeDeciderConfig,
} from '@/guide';

export { AutomationError, DEFAULT_CONFIG } from '@/types';

/** Creates a document-scoped engine; initialize after mount and dispose with the owning view. */
export function createAutomationEngine(config?: Partial<AutomationConfig>): WebAutomataAPI {
  const engine = new AutomationEngine(config);

  return {
    initialize: (formLibrary?: FormLibrary): void => {
      engine.initialize(formLibrary);
    },

    executeAction: async (
      action: ActionCommand,
      options?: ExecutionOptions
    ): Promise<ExecutionResult> => {
      return engine.executeAction(action, options);
    },

    executeActions: async (
      actions: readonly ActionCommand[]
    ): Promise<readonly ExecutionResult[]> => {
      return engine.executeActions(actions);
    },

    capturePageContext: async (): Promise<PageContext> => {
      return engine.capturePageContext();
    },

    registerForm: (formId: string, formElement: HTMLFormElement): void => {
      engine.registerForm(formId, formElement);
    },

    unregisterForm: (formId: string): void => {
      engine.unregisterForm(formId);
    },

    addEventListener: (eventType: EventType, callback: EventCallback): void => {
      engine.addEventListener(eventType, callback);
    },

    removeEventListener: (eventType: EventType, callback: EventCallback): void => {
      engine.removeEventListener(eventType, callback);
    },

    captureScreenshot: async (options?: Partial<ScreenshotOptions>): Promise<string> => {
      const context = (
        engine as unknown as {
          _contextCapture?: {
            captureScreenshot: (_options?: Partial<ScreenshotOptions>) => Promise<string>;
          };
        }
      )._contextCapture;
      if (!context) {
        throw new AutomationError('ContextCapture not initialized', 'INVALID_CONFIGURATION');
      }
      return context.captureScreenshot(options);
    },

    isInitialized: (): boolean => {
      return engine.isInitialized();
    },

    dispose: (): void => {
      engine.dispose();
    },
  };
}

export default createAutomationEngine;

export {
  createTaskAgent,
  createRemoteTaskHost,
  createAutomationTaskHost,
  installTaskBridge,
  createTypeSafeTaskDecider,
  createTaskPolicy,
  createRedactor,
  redactEnvelope,
  createResearchRequest,
  toResearchResult,
  TASK_OPERATIONS,
  TASK_DEFAULT_BUDGETS,
  TASK_REDACTED,
  TASK_BRIDGE_GLOBAL,
  TASK_BRIDGE_PROTOCOL,
  TASK_RESEARCH_PROFILE,
} from '@/agent';

export type {
  TaskRunId,
  TaskSessionId,
  TaskSnapshotId,
  TaskDocumentId,
  TaskTargetId,
  TaskOptionId,
  TaskFormId,
  TaskDialogId,
  TaskSignature,
  TaskDigest,
  TaskContextDigest,
  TaskIdPrefix,
  TaskIdFactory,
  TaskSnapshotScope,
  TaskTargetRef,
  TaskOperation,
  TaskHostOperation,
  TaskTargetOperation,
  TaskRoutineEffect,
  TaskCommitmentEffect,
  TaskEffectKind,
  TaskCommitmentClass,
  TaskArgumentSlot,
  TaskArgumentSource,
  TaskKey,
  TaskScrollDirection,
  TaskCheckedChoice,
  TaskCompletionVerdict,
  TaskAnswerChoice,
  RedactionOptions,
  Redactor,
  TaskElementKind,
  TaskCheckedState,
  TaskElementState,
  TaskOption,
  TaskCommitBasis,
  TaskCommitHint,
  TaskFormTarget,
  TaskScrollState,
  TaskElement,
  TaskElementSummary,
  TaskForm,
  TaskNotice,
  TaskDialog,
  TaskValidationMessage,
  TaskPageState,
  TaskTruncation,
  TaskUnobserved,
  TaskObservation,
  TaskObservationSummary,
  TaskSettleOptions,
  TaskHostErrorCode,
  TaskHostError,
  TaskHostResult,
  TaskHostCapabilities,
  TaskLocation,
  TaskObserveOptions,
  TaskObserveRequest,
  TaskObserveResult,
  TaskCommonCommand,
  TaskCommand,
  TaskHostCommand,
  TaskCommandRequest,
  TaskExecutionStatus,
  TaskExecutionEffect,
  TaskStaleReason,
  TaskOutcomeCode,
  TaskReadOutcome,
  TaskReadback,
  TaskNavigationInfo,
  TaskOutcomeFields,
  TaskExecutionOutcome,
  TaskHost,
  TaskBridgeMethod,
  TaskBridgeHello,
  TaskCancelRequest,
  TaskCancelAck,
  TaskReleaseRequest,
  TaskBridgePayloads,
  TaskBridgeResults,
  TaskBridgeEnvelope,
  TaskBridgeResponse,
  TaskBridgeEndpoint,
  TaskBridgeHandle,
  TaskBridgeInstallOptions,
  TaskDocumentInfo,
  TaskTransportCall,
  TaskTransportLostReason,
  TaskTransportResult,
  TaskTransport,
  RemoteTaskHostConfig,
  TaskActionExecutor,
  AutomationTaskHostConfig,
  TaskObserverConfig,
  TaskTargetResolution,
  TaskObserver,
  TaskInputValue,
  TaskInputs,
  TaskInputBinding,
  TaskInputDeclaration,
  TaskInputLeaf,
  TaskInputRule,
  TaskInputSummary,
  TaskArgumentRef,
  TaskArgumentSpec,
  TaskCandidateView,
  TaskArgumentCandidate,
  TaskCandidateSet,
  TaskArgumentView,
  TaskMaterializeContext,
  TaskArgumentAvailability,
  TaskResolvedValue,
  TaskMaterialized,
  TaskResolverRequest,
  TaskResolverResult,
  TaskResolver,
  TaskOffers,
  TaskOfferExclusion,
  TaskOfferInput,
  TaskCompileInput,
  TaskCompileErrorCode,
  TaskCompileResult,
  TaskDigestInput,
  TaskCommitField,
  TaskCommitContext,
  TaskCommitContextInput,
  TaskRedactedCommand,
  TaskActionContext,
  TaskHostCommandResult,
  TaskCandidateInput,
  TaskPostconditionInput,
  TaskLedgerInput,
  TaskDecisionStage,
  TaskHistoryKind,
  TaskHistoryEntry,
  TaskCallContext,
  TaskDeciderErrorCode,
  TaskDeciderError,
  TaskModelOption,
  TaskModelElement,
  TaskModelPageControls,
  TaskModelState,
  TaskQuestionSet,
  TaskExchangeUsage,
  TaskChoiceDiagnostics,
  TaskDeciderConfidenceProfile,
  TaskEffectiveConfidenceProfile,
  TaskProgressDiagnostics,
  TaskExchangeAttempt,
  TaskExchange,
  TaskDeciderResult,
  TaskChooseActionRequest,
  TaskTargetChoice,
  TaskActionDecision,
  TaskChooseArgumentRequest,
  TaskArgumentDecision,
  TaskClassifyCommitmentRequest,
  TaskCommitmentDecision,
  TaskVerifyCompletionRequest,
  TaskCompletionDecision,
  TaskDecider,
  TaskGoalCheck,
  TaskHttpRequest,
  TaskHttpResponse,
  TaskHttp,
  TaskRetryPolicy,
  TypeSafeTaskDeciderConfig,
  TaskGrant,
  TaskGrantEntry,
  TaskAuthorization,
  TaskNormalizedGrant,
  TaskNormalizedAuthorization,
  TaskClassifyInput,
  TaskCommitClassifier,
  TaskStructuralClassification,
  TaskApprovedOnce,
  TaskPendingCommitment,
  TaskPolicyInput,
  TaskPolicyReason,
  TaskPolicyDecision,
  TaskPolicyOptions,
  TaskPolicy,
  TaskApprovalRequest,
  TaskApprovalResolution,
  TaskExpectedValue,
  TaskPostcondition,
  TaskPostconditionStatus,
  TaskValueMatch,
  TaskPostconditionRetiredBy,
  TaskPostconditionCheck,
  TaskEffectResolutionBasis,
  TaskEffectResolution,
  TaskLedgerEntry,
  TaskEvidenceState,
  TaskEvidence,
  TaskCollectedEvidence,
  TaskExpectedState,
  TaskGateFailureCode,
  TaskGateFailure,
  TaskCompletionMode,
  TaskCompletionBasis,
  TaskAnswer,
  TaskConfidenceFloors,
  TaskExpectation,
  TaskGateInput,
  TaskGateReport,
  TaskCompletion,
  TaskVerifierInput,
  TaskVerifierResult,
  TaskVerifier,
  TaskBudgets,
  TaskBudgetUsage,
  TaskRunOptions,
  TaskProfile,
  TaskPriorEffect,
  TaskRequest,
  TaskRequirement,
  TaskPending,
  TaskCheckpointRequest,
  TaskCheckpoint,
  TaskResolution,
  TaskResumeRequest,
  TaskStatus,
  TaskBlockedReason,
  TaskFailureCode,
  TaskFailure,
  TaskWarning,
  TaskStats,
  TaskResultBase,
  TaskResult,
  TaskEventBody,
  TaskEventType,
  TaskEvent,
  TaskBeforeExecuteInfo,
  TaskAgentOptions,
  TaskAgentConfig,
  TaskAgent,
  TaskCappedValue,
  TaskQuestionBuildOptions,
  TaskHashStringFn,
  TaskSha256HexFn,
  TaskHmacSha256HexFn,
  TaskDerivedIdFn,
  TaskStableStringifyFn,
  TaskSanitizeUntrustedTextFn,
  TaskCapFieldValueFn,
  TaskCompareFieldValuesFn,
  TaskIsSensitiveKeyFn,
  TaskRedactParametersFn,
  TaskCreateRedactorFn,
  TaskRedactEnvelopeFn,
  TaskDescribeArgumentFn,
  TaskComputeOffersFn,
  TaskCompileCommandFn,
  TaskCommandDigestFn,
  TaskCommitContextFn,
  TaskContextDigestFn,
  TaskRedactCommandFn,
  TaskToHostCommandFn,
  TaskToActionCommandFn,
  TaskHasUnsafeKeyFn,
  TaskFlattenInputsFn,
  TaskInputRulesFn,
  TaskSummarizeInputsFn,
  TaskBuildCandidatesFn,
  TaskCandidateViewsFn,
  TaskArgumentViewFn,
  TaskArgumentAvailableFn,
  TaskMaterializeArgumentFn,
  TaskMergeInputsFn,
  TaskSplitSensitiveInputsFn,
  TaskCreatePolicyFn,
  TaskNormalizeAuthorizationFn,
  TaskAddRunGrantsFn,
  TaskConsumeGrantsFn,
  TaskMergeEffectsFn,
  TaskEffectForCommitmentFn,
  TaskAllCommitmentsGrantedFn,
  TaskDerivePostconditionsFn,
  TaskNormalizeOutcomeFn,
  TaskCreateLedgerEntryFn,
  TaskResolveUncertainFn,
  TaskPendingCommitmentsFn,
  TaskCheckPostconditionsFn,
  TaskCollectEvidenceFn,
  TaskExpectedStatesFn,
  TaskEvaluateGateFn,
  TaskCompletionFromReportFn,
  TaskSummarizeObservationFn,
  TaskHistoryFromLedgerFn,
  TaskBuildActionQuestionsFn,
  TaskBuildArgumentQuestionsFn,
  TaskBuildCommitmentQuestionsFn,
  TaskBuildCompletionQuestionsFn,
  TaskAssertGoalPreservedFn,
  TaskEstimateRequestBytesFn,
  TaskEstimateRequestTokensFn,
  TaskCreateTypeSafeDeciderFn,
  TaskCreateAgentFn,
  TaskCreateRemoteHostFn,
  TaskCreateObserverFn,
  TaskIsSensitiveElementFn,
  TaskCreateAutomationHostFn,
  TaskInstallBridgeFn,
  TaskCreateResearchRequestFn,
  TaskToResearchResultFn,
  ExecutionStatus,
  ExecutionEffect,
  MutationGuard,
  ActionParameterIssue,
  PressOptions,
  SetCheckedOptions,
  SelectMatchBy,
  SelectOptions,
  ScrollDirectionName,
  ScrollOptions,
  ActionCheckedState,
  ActionSubmitInfo,
  ActionOutcome,
} from '@/types';

// Types referenced by the supported public API are directly importable.
export type {
  GuideHttp,
  TaskObservedGoalLabelMatch,
  TaskObservedGoalCodeMatch,
  TaskVerifiedCurrentGoalState,
  TaskVerifiedPreparationFact,
  TaskPreservedOriginalValueFact,
  TaskSubmittedControl,
  TaskPageEvidence,
  TaskGoalRequirementView,
  ChoiceQuestion,
  TaskGoalRequirement,
  ClipRegion,
  GuideElementOperation,
  GuideOption,
  EnhancedDetectedForm,
  FormRegistryLike,
  EnhancedFormDetectorConfig,
  FormState,
} from '@/types';

export type {
  EnhancedFormField,
  DetectedFormApi,
  ChoiceCriterion,
  GuideHttpResponse,
  GuideHttpRequest,
} from '@/types';
